title: IT-блог
description: > # this means to ignore newlines until "baseurl:"
  Blog with theme Future Imperfect<br>
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://soojungson.github.io/" # the base hostname & protocol for your site, e.g. http://example.com


author:
  name: 'Soojung'
  last_name: 'Son'
  cv: '//kaptn.ru'
  avatar: '/images/avatar.jpeg'
  github_username:  soojungson  
  email: sjson@sch.ac.kr
  vk_id: 
  telegram_name:  
  logo: '/images/logo.svg'

# Build settings
markdown: kramdown

permalink: /:categories/:year/:title.html


